# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, stdenv, inputs, ... }:

let
  pkgs-unstable = inputs.hyprland.inputs.nixpkgs.legacyPackages.${pkgs.stdenv.hostPlatform.system};
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

boot = {
      # --- Initrd & early modules ---
      initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "usb_storage"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];

      initrd.kernelModules = [ "amdgpu" ];

      # Core modules (added binder + ashmem)
      kernelModules = [
        "kvm-amd"
        "binder_linux"
        "ashmem_linux"
      ];

      # Needed for Waydroid binder functionality
      extraModprobeConfig = ''
        options binder_linux devices=binder,hwbinder,vndbinder
      '';

      # --- Kernel Parameters ---
      kernelParams = [
        "quiet"
        "splash"
        "loglevel=3"
        "rd.systemd.show_status=auto"
      ];

      # --- Plymouth (Boot Splash) ---
      plymouth = {
        enable = true;
        theme = "seal_2";
        themePackages = [ pkgs.adi1090x-plymouth-themes ];
      };
      # --- Kernel Packages ---
      # CachyOS kernel for performance (use linuxPackages_cachyos if built correctly)
      # kernelPackages = pkgs.linuxPackages_latest;
      # Alternatives:
      kernelPackages = pkgs.linuxPackages_zen;
      # kernelPackages = pkgs.linuxPackages_lqx;
      # kernelPackages = pkgs.linuxPackages_cachyos;

      # --- Bootloader ---
      loader = {
            systemd-boot = {
              enable = true;
              configurationLimit = 5;
            };
            efi={
                canTouchEfiVariables = true;
                # efiSysMountPoint = "/boot";
            };
          };
      # --- Misc ---
      extraModulePackages = [ ];
    };
   
  hardware = {
    enableAllFirmware = true;
    enableRedistributableFirmware = true;

    bluetooth.enable = true;

    graphics = {
      package = pkgs-unstable.mesa;
      package32 = pkgs-unstable.pkgsi686Linux.mesa;
      enable = true;
      enable32Bit = true;
       extraPackages = with pkgs; [
         mesa
         mesa-demos
         vulkan-loader         # ensures Vulkan runtime is installed
         vulkan-validation-layers
       ];
       extraPackages32 = with pkgs; [
         pkgsi686Linux.vulkan-loader
         pkgsi686Linux.mesa
         driversi686Linux.mesa-demos
       ];
    };
  };


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/075993a8-268e-4453-8945-d768e50b4d57";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C789-ECE2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a7075876-4a84-494a-a072-73f84a279086";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c90cb3d2-feba-424e-a25b-146d24f9bd0d"; }
    ];

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
